# Utilizamos la imagen de Node.js 18 como base
FROM node:18

# Establecemos el directorio de trabajo en /usr/app
WORKDIR /usr/app

# Copiamos el archivo package.json y el archivo package-lock.json al directorio de trabajo
COPY . .
# Instalamos las dependencias del proyecto
RUN npm install

# Instalamos las dependencias del proyecto
RUN npm install -g nodemon

# Comando para iniciar la aplicación (puedes ajustarlo según tu proyecto)
CMD ["nodemon", "."]
# CMD ["nodemon", "-L"]
